In [1]:
!git clone --recursive https://github.com/Jss-on/ai8x-training.git

Cloning into 'ai8x-training'...
remote: Enumerating objects: 1760, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 1760 (delta 78), reused 99 (delta 40), pack-reused 1596
Receiving objects: 100% (1760/1760), 158.04 MiB | 28.11 MiB/s, done.
Resolving deltas: 100% (1154/1154), done.
Submodule 'datasets/face_id/facenet_pytorch' (https://github.com/MaximIntegratedAI/facenet-pytorch.git) registered for path 'datasets/face_id/facenet_pytorch'
Submodule 'distiller' (https://github.com/MaximIntegratedAI/distiller.git) registered for path 'distiller'
Cloning into '/content/ai8x-training/datasets/face_id/facenet_pytorch'...
remote: Enumerating objects: 1220, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (5/5), done.        
remote: Total 1220 (delta 0), reused 2 (delta 0), pack-reused 1215        
Receiving objects: 100% (1220/1220), 22.86 MiB | 22.66 MiB/s, done.
Resolvin

#Run below if your data comes from kaggle

In [2]:
!pip install -q kaggle


In [3]:
!mkdir -p ~/.kaggle
!cp /content/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [4]:
!kaggle datasets download -d tensordt/smarte2

 95% 28.0M/29.6M [00:02<00:00, 17.6MB/s]
100% 29.6M/29.6M [00:02<00:00, 14.5MB/s]


##Create data folder and under that directory, create raw and processed folders

In [5]:
import os

# Define the root directory
root_directory = "/content/ai8x-training"

# Define the folders to be created
data_folder = os.path.join(root_directory, "data")
raw_folder = os.path.join(data_folder, "raw")
processed_folder = os.path.join(data_folder, "processed")

# Create the folders if they don't already exist
os.makedirs(raw_folder, exist_ok=True)
os.makedirs(processed_folder, exist_ok=True)

print("Folders created successfully!")


Folders created successfully!


In [6]:
!unzip /content/smarte2.zip -d /content/ai8x-training/data/raw

Archive:  /content/smarte2.zip
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak1.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak10.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak11.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak12.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak13.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak14.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak15.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak16.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak17.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak18.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak19.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak2.wav  
  inflating: /content/ai8x-training/data/raw/Full_leak4/Full_leak20.wav  
  inflati

In [7]:
cd /content/ai8x-training

/content/ai8x-training


In [8]:
!sudo apt-get update
!sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git
!curl https://pyenv.run | bash
!echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
!echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
!echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:5 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [897 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [980 kB]
Get:13 http://security.ubuntu.com/ubun

#Step by step process on SHELL below
1. pyenv install 3.8.11
2. pyenv local 3.8.11
3. python -m venv venv --prompt ai8x-training
4. source venv/bin/activate
5. pip3 install -U pip wheel setuptools
6. pip3 install -r requirements-cu11.txt
7. pip3 install -r requirements.txt
8. chmod +x /content/ai8x-training/scripts/train_smart_echo_net.sh
9. scripts/train_smart_echo_net.sh


In [ ]:
!exec $SHELL

Streaming output truncated to the last 5000 lines.
==> Confusion:
[[117  41  16   0   0   0]
 [ 45  57   4   0   0   0]
 [ 14  12 124  15   0   0]
 [  0   1  13 171  18   0]
 [  0   0   2  38 173   0]
 [  0   0   0   0   0   0]]

==> Best [Top1: 75.842   Top5: 100.000   Sparsity:0.00   Params: 113050 on epoch: 56]
Saving checkpoint to: logs/2023.08.18-022226/qat_checkpoint.pth.tar


Training epoch: 7752 samples (256 per mini-batch)
Epoch: [69][   10/   31]    Overall Loss 0.000295    Objective Loss 0.000295                                        LR 0.001000    Time 0.112776    
Epoch: [69][   20/   31]    Overall Loss 0.000301    Objective Loss 0.000301                                        LR 0.001000    Time 0.084415    
Epoch: [69][   30/   31]    Overall Loss 0.000315    Objective Loss 0.000315    Top1 100.000000    Top5 100.000000    LR 0.001000    Time 0.069139    
Epoch: [69][   31/   31]    Overall Loss 0.000312    Objective Loss 0.000312    Top1 100.000000    Top5 100.000000 

#Step by step process on SHELL above
1. pyenv install 3.8.11
2. pyenv local 3.8.11
3. python -m venv venv --prompt ai8x-training
4. source venv/bin/activate
5. pip3 install -U pip wheel setuptools
6. pip3 install -r requirements-cu11.txt
7. pip3 install -r requirements.txt
8. chmod +x /content/ai8x-training/scripts/train_smart_echo_net.sh
9. scripts/train_smart_echo_net.sh

In [ ]:
import shutil

# Path to the directory you want to zip
directory_path = "/content/don/ai8x-synthesis/tensorflow/tf-maxstutnet"

# Destination zip file path
zip_file_path = "/content/don/ai8x-synthesis/tensorflow/tf-maxstutnet.zip"

# Create the zip file
shutil.make_archive(zip_file_path, 'zip', directory_path, directory_path)


'/content/don/ai8x-synthesis/tensorflow/tf-maxstutnet.zip.zip'